name       : numix-gtk-theme
version    : 2.3.20150810
release    : 3
source     :
    - http://ppa.launchpad.net/numix/ppa/ubuntu/pool/main/n/numix-gtk-theme/numix-gtk-theme_2.3+344~201508102301~ubuntu15.04.1.tar.xz : e75cc4dd267c49ce0df03fefdc777cf5f9d8186320366eec13c8fd6d0d689a59
license    : GPL-3.0
summary    : Numix GTK Theme
description: |
    Numix GTK Theme
rundeps    :
    - gtk2-engine-murrine
install    : |
    mkdir -p %installroot%/usr/share/themes/Numix
    rm -rf debian metacity-1 openbox-3 unity xfce-notify-4.0 xfwm4
    cp -r * %installroot%/usr/share/themes/Numix
