name       : numix-gtk-theme
version    : 2.3.201505232016
release    : 1
source     :
    - http://ppa.launchpad.net/numix/ppa/ubuntu/pool/main/n/numix-gtk-theme/numix-gtk-theme_2.3+340~201505232016~ubuntu15.04.1.tar.xz : ad5337273646895bcb2b3b690bbda1bb30e582e4968f66ada5c9c78280fceeef
license    : GPL-3.0
summary    : Numix GTK Theme
description: |
    Numix GTK Theme
builddeps  :
setup      : |
build      : |
install    : |
    mkdir -p %installroot%/usr/share/themes/Numix
    rm -r debian metacity-1 openbox-3 unity xfce-notify-4.0 xfwm4
    mv * %installroot%/usr/share/themes/Numix
