name       : numix-gtk-theme
version    : 2.6.6
release    : 6
source     :
    - https://github.com/numixproject/numix-gtk-theme/archive/2.6.6.tar.gz : 5ee5ed54bea10fe23c99f1fcc614cbf593764b6310cdf889723f8c251abf0856
license    : GPL-3.0
component  : desktop.theme
summary    : Numix GTK Theme
description: |
    Numix GTK Theme
builddeps  :
    - pkgconfig(gdk-pixbuf-2.0)
    - ruby-sass
rundeps    :
    - gtk2-engine-murrine
install    : |
    %make_install
    for dir in openbox-3 unity xfce-notify-4.0 xfwm4; do
        rm -rf $installdir/usr/share/themes/Numix/$dir
    done
