name       : numix-gtk-theme
version    : 2.6.7
release    : 9
source     :
    - git|https://github.com/numixproject/numix-gtk-theme : ad4b345cb19edba96bec72d6dc97ed1b568755a8
homepage   : https://github.com/numixproject/numix-gtk-theme
license    : GPL-3.0-or-later
component  : desktop.theme
summary    : Numix GTK Theme
description: |
    A modern flat theme with a combination of light and dark elements.
builddeps  :
    - pkgconfig(gdk-pixbuf-2.0)
    - sassc
rundeps    :
    - gtk2-engine-murrine
setup      : |
    %patch -p1 < $pkgfiles/Fix-gtk-dark-error.patch
install    : |
    %make_install
    for dir in openbox-3 unity; do
        rm -rf $installdir/usr/share/themes/Numix/$dir
    done
