name       : numix-gtk-theme
version    : 2.6.5
release    : 4
source     :
    - https://github.com/numixproject/numix-gtk-theme/archive/2.6.5.tar.gz : 0511b9a183324e81a72118016844726bd965e5a763490383dda539d56b44f1b7
license    : GPL-3.0
component  : desktop.theme
summary    : Numix GTK Theme
description: |
    Numix GTK Theme
builddeps  :
    - pkgconfig(gdk-pixbuf-2.0)
    - ruby-sass
rundeps    :
    - gtk2-engine-murrine
install    : |
    %make_install
    for dir in metacity-1 openbox-3 unity xfce-notify-4.0 xfwm4; do
        rm -rf $installdir/usr/share/themes/Numix/$dir
    done
