name       : numix-gtk-theme
version    : 2.3.2015019
release    : 2
source     :
    - http://ppa.launchpad.net/numix/ppa/ubuntu/pool/main/n/numix-gtk-theme/numix-gtk-theme_2.3+341~201506190531~ubuntu15.04.1.tar.xz : 46b6e616b3fa4e0d9eddab3f38bd7cc4b3b01a329e712162d0a73057005fe3bc
license    : GPL-3.0
summary    : Numix GTK Theme
description: |
    Numix GTK Theme
rundeps    :
    - gtk2-engine-murrine
install    : |
    mkdir -p %installroot%/usr/share/themes/Numix
    rm -rf debian metacity-1 openbox-3 unity xfce-notify-4.0 xfwm4
    cp -r * %installroot%/usr/share/themes/Numix
