name       : numix-gtk-theme
version    : 2.6.7
release    : 7
source     :
    - https://github.com/numixproject/numix-gtk-theme/archive/2.6.7.tar.gz : 2b997ad3eee0b802d0dd49dd772127fd3c337cca32d8863efd4897928e38879a
license    : GPL-3.0
component  : desktop.theme
summary    : Numix GTK Theme
description: |
    Numix GTK Theme
builddeps  :
    - pkgconfig(gdk-pixbuf-2.0)
    - ruby-sass
rundeps    :
    - gtk2-engine-murrine
install    : |
    %make_install
    for dir in openbox-3 unity xfce-notify-4.0 xfwm4; do
        rm -rf $installdir/usr/share/themes/Numix/$dir
    done
